version: "3.9"

services:
  s3-file-manager:
    container_name: s3mgr

    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: s3-file-manager

    mem_limit: 512m
    cpus: 0.5

    ports:
      - "80:80"

    volumes:
      - ../app/data:/app/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
